version: '3'
services:
  app:
    build: .
    container_name: node-app
    restart: always
    ports:
      - "4000:4000"  # Expose port 4000
    networks:
      - app-network
    environment:
      - NODE_ENV=production

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "8080:80"  # Expose port 80 for Nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Mount the Nginx config file
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

